// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	Config
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Project          []*Config_Project `protobuf:"bytes,1,rep,name=project" json:"project,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto1.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetProject() []*Config_Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type Config_Project struct {
	ProjectId        *string  `protobuf:"bytes,1,opt,name=project_id" json:"project_id,omitempty"`
	Domain           []string `protobuf:"bytes,2,rep,name=domain" json:"domain,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Config_Project) Reset()                    { *m = Config_Project{} }
func (m *Config_Project) String() string            { return proto1.CompactTextString(m) }
func (*Config_Project) ProtoMessage()               {}
func (*Config_Project) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Config_Project) GetProjectId() string {
	if m != nil && m.ProjectId != nil {
		return *m.ProjectId
	}
	return ""
}

func (m *Config_Project) GetDomain() []string {
	if m != nil {
		return m.Domain
	}
	return nil
}

func init() {
	proto1.RegisterType((*Config)(nil), "proto.Config")
	proto1.RegisterType((*Config_Project)(nil), "proto.Config.Project")
}

func init() { proto1.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xf1, 0x5c, 0x6c,
	0xce, 0x60, 0x61, 0x21, 0x35, 0x2e, 0x76, 0xa0, 0x50, 0x56, 0x6a, 0x72, 0x89, 0x04, 0xa3, 0x02,
	0xb3, 0x06, 0xb7, 0x91, 0x28, 0x44, 0xa5, 0x1e, 0x44, 0x5e, 0x2f, 0x00, 0x22, 0x29, 0xa5, 0xcb,
	0xc5, 0x0e, 0x65, 0x0a, 0x09, 0x71, 0x71, 0x41, 0xb5, 0xc4, 0x67, 0xa6, 0x00, 0x75, 0x31, 0x6a,
	0x70, 0x0a, 0xf1, 0x71, 0xb1, 0xa5, 0xe4, 0xe7, 0x26, 0x66, 0xe6, 0x49, 0x30, 0x01, 0x4d, 0xe1,
	0x04, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x9a, 0xff, 0x94, 0x76, 0x00, 0x00, 0x00,
}
